[package]
name = "extract-audio"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.35", features = ["derive"] }

polars = { version = "0.46.0", features = ["full"] }

parquet = { version = "54.3.1" }
arrow = { version = "54.3.1" }

tempfile = "3"

rayon = { version = "1.10.0" }

[profile.release]
opt-level = 3
lto = true
